trigger:
- main

pool:
  name: 'ec2'

variables:
  dockerImageName: flask
  dockerImageTag: $(Build.BuildId)

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - script: |
        docker build -f Dockerfiletest --target test -t $(dockerImageName):$(dockerImageTag) .
        docker create -ti --name testcontainer $(dockerImageName):$(dockerImageTag)
        docker cp testcontainer:/app/test-results.xml $(Build.ArtifactStagingDirectory)/testresults
        docker rm -fv testcontainer 
        

