trigger:
  branches:
    include:
      - main
  manual:
    enabled: true

pool: ec2

variables:
  dockerImageName: 'flask-counter-service'
  dockerImageTag: ${{ coalesce(variables['Build.SourceBranchName'], 'latest') }}

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build and Test'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DdockerHub'  # Specify the connection to your Docker Hub registry
        command: 'build'
        Dockerfile: '**/Dockerfiletest'
        tags: '$(dockerImageName):$(dockerImageTag)'

    - task: Docker@2
      inputs:
        containerRegistry: 'DdockerHub'  # Specify the connection to your Docker Hub registry
        command: 'push'
        repository: '$(dockerImageName)'
        tags: '$(dockerImageTag)'
      condition: succeeded()

