trigger:
- main

pool:
  name: ec2

variables:
  dockerImageName: 'blackrussian84/flask'
  dockerImageTag: 'latest'

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'dockerhub'  # Replace with your Docker service connection name
    repository: '$(dockerImageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(dockerImageTag)'

- task: Docker@2
  displayName: 'Run pytest in Docker container'
  inputs:
    containerRegistry: 'dockerub'  # Replace with your Docker service connection name
    repository: '$(dockerImageName)'
    command: 'build'
    arguments: 'pytest -v test_app.py --junitxml=test-results.xml'
    tags: '$(dockerImageTag)'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
  condition: succeededOrFailed()